/**
 * Build script: TS source -> deployable package.
 *
 * Three artifacts:
 *  - lib/index.js — host loader entry (exports["."] / main), loaded by the
 *    dsh Node process (zod bundled in; the projection registry only calls
 *    schema.parse duck-typed, no instanceof checks, so bundling is safe).
 *  - lib/client.js — browser bundle in ModuleLoader.load format; react stays
 *    external (shell singleton, ModuleLoader resolves it).
 *  - cordis.patch.yml — regenerated from rates.yml on every build: the rates
 *    dict rides the patch config so it reaches the plugin's composition layer.
 *    dsh 0.1.7 unifies settings namespaces with plugin Config exports, and the
 *    settings page's base/prefill view reads exactly that composition layer —
 *    without it a fresh install would show an empty rate table there.
 *
 * Prerequisites: `npm install` (brings esbuild + zod into ./node_modules).
 */
import { build, context } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

const watch = process.argv.includes('--watch');

const nodePaths = [fileURLToPath(new URL('./node_modules', import.meta.url))];

const hostOptions = {
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  nodePaths,
  outfile: 'lib/index.js',
  sourcemap: true,
  logLevel: 'info',
  // 保留 UTF-8 源码字符（默认 ascii 会把中文注释/字符串转成 \uXXXX，产物难读）
  charset: 'utf8',
  // yaml 是 CJS：ESM 产物里的动态 require 需要真 require 兜底，否则报 "Dynamic require of ..."
  banner: {
    js: "import { createRequire } from 'node:module';\nconst require = createRequire(import.meta.url);",
  },
};

const clientOptions = {
  entryPoints: ['src/client.ts'],
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  target: 'es2022',
  nodePaths,
  outfile: 'lib/client.js',
  // react 走 shell 单例（ModuleLoader 的 require 解析到 seed 里的 react），
  // 不能打进 bundle——否则双 React 实例会崩掉 slots 渲染。
  external: ['react', 'react/jsx-runtime', 'react-dom', 'react-dom/client'],
  // 同上：中文文案（账单标题等）保持 UTF-8 原样输出，不转义
  charset: 'utf8',
  banner: {
    js: [
      'window.__ModuleLoader__.load({',
      '  id: "meow-cachebilling",',
      '  factory: (require) => {',
      '    var module = { exports: {} };',
      '    var exports = module.exports;',
    ].join('\n'),
  },
  footer: {
    js: ['    return module.exports;', '  }', '});'].join('\n'),
  },
  sourcemap: true,
  logLevel: 'info',
};

if (watch) {
  await (await context(hostOptions)).watch();
  await (await context(clientOptions)).watch();
  console.log('[build] watching src/ for changes...');
} else {
  await Promise.all([build(hostOptions), build(clientOptions)]);
}

// ── cordis.patch.yml：config 段 = rates.yml 预填层（键同 host 的 entryKey）────
// 预填层必须住进组合层：0.1.7 设置页的 base/预填视图 = 插件组合层，apply 拿到的
// config = 组合⊕用户。手改无效——本文件每次 build 从 rates.yml 再生成。
const ratesPath = fileURLToPath(new URL('./rates.yml', import.meta.url));
const patchPath = fileURLToPath(new URL('./cordis.patch.yml', import.meta.url));
try {
  const models = parseYaml(readFileSync(ratesPath, 'utf8')).models;
  const entryKey = (e) => `${(e.provider ?? '*').toLowerCase()}/${e.model.toLowerCase()}`;
  const config = Object.fromEntries(models.map((e) => [entryKey(e), e]));
  const doc = [
    '# meow-cachebilling bundle patch: inserts this plugin into a profile layer stack.',
    '# GENERATED by build.mjs from rates.yml — 预填价目随发版更新，手改会被下次 build 覆盖。',
    '# Applied when a profile lists this bundle (or wired by dev_install_package).',
    stringifyYaml([{ insert: [{ id: 'meow-cachebilling', name: 'meow-cachebilling', config }] }]),
  ].join('\n');
  writeFileSync(patchPath, doc);
  console.log(`[build] cordis.patch.yml regenerated (prefill ${models.length} entries)`);
} catch (e) {
  console.warn('[build] cordis.patch.yml 生成失败（保留现有文件）：', e);
}
