/**
 * Build script: TS source -> deployable package.
 *
 * Three artifacts:
 *  - lib/index.js — host loader entry (exports["."] / main), loaded by the
 *    dsh Node process (zod bundled in; the projection registry only calls
 *    schema.parse duck-typed, no instanceof checks, so bundling is safe).
 *  - lib/client.js — browser bundle in ModuleLoader.load format; react stays
 *    external (shell singleton, ModuleLoader resolves it).
 *  - cordis.patch.yml — regenerated on every build: insert-only bundle mount
 *    declaration. The rates dict no longer rides the patch config: dsh 0.1.7
 *    rejects any settings write whose value differs from the fully merged
 *    patch result (config-editor edit equality check), which a prefill-filled
 *    patch makes unreachable.
 *  - src/prefill.gen.ts — regenerated from rates.yml on every build: the
 *    settings page's prefill snapshot for the client bundle (0.1.7's base view
 *    is filled from schema defaults, and a dict(any) root cannot declare
 *    per-key defaults, so the client carries the table itself).
 *
 * Prerequisites: `npm install` (brings esbuild + zod into ./node_modules).
 */
import { build, context } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

const watch = process.argv.includes('--watch');

const nodePaths = [fileURLToPath(new URL('./node_modules', import.meta.url))];

const hostOptions = {
  entryPoints: ['src/index.ts'],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  nodePaths,
  outfile: 'lib/index.js',
  sourcemap: true,
  logLevel: 'info',
  // 保留 UTF-8 源码字符（默认 ascii 会把中文注释/字符串转成 \uXXXX，产物难读）
  charset: 'utf8',
  // yaml 是 CJS：ESM 产物里的动态 require 需要真 require 兜底，否则报 "Dynamic require of ..."
  banner: {
    js: "import { createRequire } from 'node:module';\nconst require = createRequire(import.meta.url);",
  },
};

const clientOptions = {
  entryPoints: ['src/client.ts'],
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  target: 'es2022',
  nodePaths,
  outfile: 'lib/client.js',
  // react 走 shell 单例（ModuleLoader 的 require 解析到 seed 里的 react），
  // 不能打进 bundle——否则双 React 实例会崩掉 slots 渲染。
  external: ['react', 'react/jsx-runtime', 'react-dom', 'react-dom/client'],
  // 同上：中文文案（账单标题等）保持 UTF-8 原样输出，不转义
  charset: 'utf8',
  banner: {
    js: [
      'window.__ModuleLoader__.load({',
      '  id: "meow-cachebilling",',
      '  factory: (require) => {',
      '    var module = { exports: {} };',
      '    var exports = module.exports;',
    ].join('\n'),
  },
  footer: {
    js: ['    return module.exports;', '  }', '});'].join('\n'),
  },
  sourcemap: true,
  logLevel: 'info',
};

// ── 生成物（build 前跑：client bundle 要吃 prefill.gen.ts）─────────────────
// cordis.patch.yml：insert 行 = bundle 装载声明。
// 0.1.6：config 段曾是 rates.yml 预填层（键同 host 的 entryKey）。
// 0.1.7 起 settings 写入有「home patch 覆盖」检查（config-editor:edit 写盘前把
// 全量 patch 合并结果与写入值做全等比对，不一致即拒——meow-memory 2026-09-25 实
// 证同款死锁）。预填表住进 patch config 后合并结果永远多出 rates 键 → 设置页永
// 远拒写。故 rates 预填不再进 patch：insert 行只留装载声明；费率兜底走包根
// rates.yml（host 侧 COMPILED_PREFILL），rates.yml 文件不受影响。
// src/prefill.gen.ts：设置页预填层的 client 侧快照。0.1.7 设置页 base 视图 =
// 宿主 resolveConfig 按 schema 键深填默认值，dict(any) 根声明不了按键默认 →
// 官方通道装不下预填表，改由 client bundle 自带（组件垫在 base 底层，host base
// 在场时优先——0.1.6 腿的 base 就是运行时 rates.yml）。手改会被下次 build 覆盖。
const ratesPath = fileURLToPath(new URL('./rates.yml', import.meta.url));
const patchPath = fileURLToPath(new URL('./cordis.patch.yml', import.meta.url));
const prefillGenPath = fileURLToPath(new URL('./src/prefill.gen.ts', import.meta.url));
try {
  const models = parseYaml(readFileSync(ratesPath, 'utf8')).models;
  const entryKey = (e) => `${(e.provider ?? '*').toLowerCase()}/${e.model.toLowerCase()}`;
  const prefill = Object.fromEntries(models.map((e) => [entryKey(e), e]));
  const doc = [
    '# meow-cachebilling bundle patch: inserts this plugin into a profile layer stack.',
    '# GENERATED by build.mjs — 手改会被下次 build 覆盖。',
    '# Applied when a profile lists this bundle (or wired by dev_install_package).',
    '# 0.1.7 起 config 预填不再写入（settings 写入的 home-patch 覆盖检查会拒）——',
    '# rates 兜底在包根 rates.yml（host 侧 COMPILED_PREFILL），无需住在 patch 里。',
    stringifyYaml([{ insert: [{ id: 'meow-cachebilling', name: 'meow-cachebilling' }] }]),
  ].join('\n');
  writeFileSync(patchPath, doc);
  const gen = [
    '/**',
    ' * GENERATED by build.mjs from rates.yml — 设置页预填层（client 侧编译期快照）。',
    ' * 手改无效：每次 build 从包根 rates.yml 再生成。键 = 「provider/model」',
    ' * （entryKey，与 host 预填层/设置页 user 层同一命名空间）。',
    ' */',
    `export const PREFILL_RATES: Record<string, unknown> = ${JSON.stringify(prefill, null, 2)};`,
    '',
  ].join('\n');
  writeFileSync(prefillGenPath, gen);
  console.log(`[build] cordis.patch.yml (insert-only) + src/prefill.gen.ts regenerated (${models.length} rates entries)`);
} catch (e) {
  console.warn('[build] 生成失败（保留现有 cordis.patch.yml / prefill.gen.ts）：', e);
}

if (watch) {
  await (await context(hostOptions)).watch();
  await (await context(clientOptions)).watch();
  console.log('[build] watching src/ for changes...');
} else {
  await Promise.all([build(hostOptions), build(clientOptions)]);
}
