/**
 * GENERATED by build.mjs from rates.yml — 设置页预填层（client 侧编译期快照）。
 * 手改无效：每次 build 从包根 rates.yml 再生成。键 = 「provider/model」
 * （entryKey，与 host 预填层/设置页 user 层同一命名空间）。
 */
export const PREFILL_RATES: Record<string, unknown> = {
  "deepseek-official/deepseek-v4-flash": {
    "model": "deepseek-v4-flash",
    "provider": "deepseek-official",
    "timezone": "Asia/Shanghai",
    "peak": {
      "hit": 0.04,
      "miss": 2,
      "output": 8,
      "when": [
        {
          "days": [
            "mon",
            "tue",
            "wed",
            "thu",
            "fri"
          ],
          "ranges": [
            "09:00-12:00",
            "14:00-18:00"
          ]
        }
      ]
    },
    "valley": {
      "hit": 0.02,
      "miss": 1,
      "output": 4
    },
    "cacheSaving": null
  },
  "deepseek-official/deepseek-v4-flash-vision-exp": {
    "model": "deepseek-v4-flash-vision-exp",
    "provider": "deepseek-official",
    "timezone": "Asia/Shanghai",
    "peak": {
      "hit": 0.04,
      "miss": 2,
      "output": 8,
      "when": [
        {
          "days": [
            "mon",
            "tue",
            "wed",
            "thu",
            "fri"
          ],
          "ranges": [
            "09:00-12:00",
            "14:00-18:00"
          ]
        }
      ]
    },
    "valley": {
      "hit": 0.02,
      "miss": 1,
      "output": 4
    },
    "cacheSaving": null
  },
  "deepseek-official/deepseek-v4-pro": {
    "model": "deepseek-v4-pro",
    "provider": "deepseek-official",
    "timezone": "Asia/Shanghai",
    "peak": {
      "hit": 0.3,
      "miss": 9,
      "output": 27,
      "when": [
        {
          "days": [
            "mon",
            "tue",
            "wed",
            "thu",
            "fri"
          ],
          "ranges": [
            "09:00-12:00",
            "14:00-18:00"
          ]
        }
      ]
    },
    "valley": {
      "hit": 0.15,
      "miss": 4.5,
      "output": 13.5
    },
    "cacheSaving": null
  },
  "zai-coding-cn/glm-5.3": {
    "model": "glm-5.3",
    "provider": "zai-coding-cn",
    "timezone": "Asia/Shanghai",
    "const": {
      "hit": 0,
      "miss": 8,
      "output": 28
    },
    "cacheSaving": null
  },
  "zai-coding-cn/glm-5.2": {
    "model": "glm-5.2",
    "provider": "zai-coding-cn",
    "timezone": "Asia/Shanghai",
    "const": {
      "hit": 0,
      "miss": 8,
      "output": 28
    },
    "cacheSaving": null
  },
  "zai-coding-cn/glm-5.3-flash": {
    "model": "glm-5.3-flash",
    "provider": "zai-coding-cn",
    "timezone": "Asia/Shanghai",
    "const": {
      "hit": 0.115,
      "miss": 0.4,
      "output": 1.4
    },
    "cacheSaving": null
  }
};
